development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: comics_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: comics_test
  pool: 5
  username: postgres

production:
  username: mucpcarbnrfemj
  database: deffh9icnlf14c
  host: ec2-54-225-103-9.compute-1.amazonaws.com
